Updates for installing under rhel 8
Cacti/documentation pull request #166
Opened 2022-12-20 17:42 UTC by bmfmancini

2022-12-21 11:33 UTC, netniV requested changes

2022-12-21 11:33 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +### For Centos/RHEL/ROCKY 8+
This should not be a sub heading, consider using sub items, eg, 

```md
1. Enable Epel repo to enable PHP 7.2 package download 
   1.1 For CentOS 7.x/RHEL 7.x and below:
   ```console
   blah

   ...

   1.2 For CentOS 8.x/RHEL 8.x and above:
   ```console
   blah
```

2022-12-21 11:33 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +##### for RHEL/CENTOS/ROCKY 8+
Subtitle usage is inconsistent, see above comment about using list items intead

2022-12-22 19:25 UTC, bmfmancini commented
Added some more updates to install docs

2022-12-23 12:28 UTC, netniV requested changes
Good work, think we need tighten up a few bits but looking good.

2022-12-23 12:28 UTC, netniV commented on General-Installing-Instructions.md
> +this can be set by editing the following section of config.php
This may be a confusing statement.  If any proxy servers are used, the headers containing the IP must be defined.  Not the actual IP etc.

2022-12-23 12:28 UTC, netniV commented on General-Installing-Instructions.md
> +this can be set by editing the following section of config.php
Also, why are we creating a separate page for this? Should this not be part of an existing one?

2022-12-23 12:28 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +1.1 For Centos/RHEL/ROCKY 8+
Not sure the indentation is correct.

2022-12-23 12:28 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +1.2 For RHEL/CENTOS/ROCKY 7.x and below
Not sure the indentation is correct.

2022-12-23 12:28 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +### Considerations when using Proxys in front of Cacti (Cacti 1.2.23+)
Proxies not proxys

2022-12-23 12:28 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> + *   - array of one or more the following:
This is a duplicate of the other section.  We should make a small comment and link to the full section if it is in more than one place.

2022-12-23 12:28 UTC, netniV commented on Installing-Under-Ubuntu-Debian.md
> + *		'X-Real-IP',
Duplicated see earlier comment.

2023-01-02 01:35 UTC, merged