Add PHP FPM notice to install instructions
Cacti/documentation pull request #171
Opened 2023-01-06 21:25 UTC by bmfmancini

2023-01-06 21:31 UTC, netniV requested changes

2023-01-06 21:31 UTC, netniV commented on General-Installing-Instructions.md
> +  ```
incorrect indentation

2023-01-06 21:31 UTC, netniV commented on Installing-Under-Ubuntu-Debian.md
> +   ```
incorrect indentation

2023-01-06 21:37 UTC, bmfmancini commented
@netniV  I have updated the spacing

2023-01-06 21:45 UTC, netniV requested changes

2023-01-06 21:45 UTC, netniV commented on General-Installing-Instructions.md
> + systemctl restart php-fpm
space :)

2023-01-06 21:45 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> + systemctl restart php-fpm
space :)

2023-01-06 21:45 UTC, netniV commented on Installing-Under-Ubuntu-Debian.md
> +   ```
Still incorrect.

2023-01-18 13:38 UTC, TheWitness commented
Is this ready to merge?

2023-01-18 13:39 UTC, TheWitness submitted a review, later dismissed

2023-01-18 18:35 UTC, netniV commented
No, still outstanding indentation issues :)

2023-01-20 09:25 UTC, netniV requested changes

2023-01-20 09:25 UTC, netniV commented on Cacti-SSL-Configuration.md
> -```console
You seem to have lost the example code markers

2023-01-20 09:25 UTC, netniV commented on Cacti-SSL-Configuration.md
> ----
Missing separator

2023-01-20 09:25 UTC, netniV commented on Cacti-SSL-Configuration.md
> +### Note: If your Cacti system is public
This is not a full title and looks wrong.

2023-01-20 09:25 UTC, netniV commented on Cacti-SSL-Configuration.md
> +## Note, if using multiple pollers
This is not a title and looks wrong

2023-01-25 01:01 UTC, netniV requested changes
Couple of suggestions.

2023-01-25 01:01 UTC, netniV commented on Cacti-SSL-Configuration.md
> +
Extra space at start of bash code

2023-01-25 01:01 UTC, netniV commented on Cacti-SSL-Configuration.md
>  all must have HTTPS enabled for the remote polling feature to work properly.
I think we should update this to something like 

# Remote Poller Setup

When using remote pollers, you MUST enable SSL between the main and remote pollers.  Cacti will not function without secure communications.

2023-01-25 01:12 UTC, netniV requested changes
This PR is messy with the bad changes from the editor that didn't care properly about rulesets.  It may be worth creating a diff, checking for actual changes vs format changes, then reapply the actual changes to a fresh branch.  After that, applying any formatting rules as necessary so that things like indentation and breaks are properly applied.  

Reach out to me if you have any questions.

2023-01-25 01:12 UTC, netniV commented on Cacti-SSL-Configuration.md
> -```
Missing code markers

2023-01-25 01:12 UTC, netniV commented on Data-Source-Templates.md
> +<https://github.com/Cacti/documentation/blob/develop/Variables.md>
This seems to be a link but is done as an HTML tag?  Is this correct?

2023-01-25 01:12 UTC, netniV commented on General-Installing-Instructions.md
> +   systemctl restart php-fpm
Space indentations

2023-01-25 01:12 UTC, netniV commented on Graph-Templates.md
> +for all classes of **Devices** using the **Graph Template**.
This is one kinds of area where sticking to the 80 column limit should be avoided.  Tables are not so easy to read when they are split like this.

2023-01-25 01:12 UTC, netniV commented on Graph-Templates.md
> +- **Name** - This is the name that you provide to the **Graph Template**.Since Cacti
Missing space?

2023-01-25 01:12 UTC, netniV commented on Graph-Templates.md
> + that you create using the **Device Template**.
Indentation is wrong

2023-01-25 01:12 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +
Incorrect indentation

2023-01-25 01:12 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +3.Enable and start the service to ensure it starts when the system reboots
Space missing

2023-01-25 01:12 UTC, netniV commented on Install-Under-CentOS_LAMP.md
> +   IDENTIFIED BY 'your_cacti_password';
Did not need splitting

2023-06-03 15:45 UTC, TheWitness commented
@bmfmancini, can you work on the outstanding comments.  @netniV, if they are resolved, can you mark such so that we can merge?

2023-06-03 15:48 UTC, bmfmancini commented
Netniv was going to look at this one from what I remember differences
between the MD standards and our doc standards

On Sat, Jun 3, 2023, 11:45 AM TheWitness ***@***.***> wrote:

> @bmfmancini <https://github.com/bmfmancini>, can you work on the
> outstanding comments. @netniV <https://github.com/netniV>, if they are
> resolved, can you mark such so that we can merge?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cacti/documentation/pull/171#issuecomment-1575030806>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGEXTBBSGV7FDHRNN2A24LXJNL2TANCNFSM6AAAAAATTPFKKQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-05 02:06 UTC, netniV commented
Yeah I was trying to find a way to make it easier for @bmfmancini to comply with our normal doc standards using an editor such as VSC.  i'll try and get back on that this week.

2023-07-21 23:11 UTC, TheWitness commented
Where is this at?

2023-07-23 01:33 UTC, netniV commented
Checkout Pull 177, which has seans changes, plus my improvements and should close this one when merged.

2023-07-23 21:35 UTC, closed without merging